# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 20, size = (4, 7))
a

array([[18, 14,  1, 11, 13, 18,  4],
       [ 1, 12, 15, 10, 12,  5, 16],
       [16,  8,  3,  9, 10,  2,  2],
       [17, 14,  9,  1,  4, 11,  2]])

In [3]:
a/20

array([[0.9 , 0.7 , 0.05, 0.55, 0.65, 0.9 , 0.2 ],
       [0.05, 0.6 , 0.75, 0.5 , 0.6 , 0.25, 0.8 ],
       [0.8 , 0.4 , 0.15, 0.45, 0.5 , 0.1 , 0.1 ],
       [0.85, 0.7 , 0.45, 0.05, 0.2 , 0.55, 0.1 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
b = np.random.randint(0, 10, size = (8, 10))
b

array([[6, 2, 7, 9, 1, 6, 2, 8, 4, 3],
       [3, 3, 5, 0, 5, 1, 0, 2, 1, 2],
       [0, 4, 7, 2, 2, 3, 1, 3, 2, 9],
       [8, 2, 6, 9, 7, 8, 4, 5, 5, 1],
       [1, 7, 7, 0, 4, 2, 4, 9, 1, 8],
       [6, 2, 9, 4, 5, 0, 1, 3, 8, 2],
       [2, 6, 5, 6, 6, 6, 9, 5, 6, 4],
       [0, 2, 2, 4, 4, 5, 1, 8, 8, 3]])

In [5]:
min_ind = b.sum(axis=1).argmin()
print(min_ind, b[min_ind])

1 [3 3 5 0 5 1 0 2 1 2]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [6]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

In [7]:
point_1 = np.array([1,36,7,9])
point_2 = np.array([45,79,4,7])
distance = np.sqrt(np.dot(point_1-point_2, point_1-point_2))
print(distance)

61.62791575252241


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [8]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

x = np.linalg.inv(A)@(-C)@np.linalg.inv(B)
x

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
data = np.loadtxt('data/minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)

In [10]:
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [11]:
np.average(data[:,1:], axis=0), np.min(data[:,1:], axis=0), np.max(data[:,1:], axis=0), np.median(data[:,1:], axis=0)

(array([2.16010017e+04, 9.05528000e+00]),
 array([0, 1]),
 array([2147483647,         39]),
 array([40.,  9.]))

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [12]:
q = np.quantile(data[:,1], 0.75)
q

65.0

In [13]:
filtred_data = data[data[:,1]<q]
filtred_data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

In [14]:
filtred_data[:,1].max()

64

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [15]:
len(data[data[:,1]==0])

479

In [16]:
data[data[:,1]==0, 1] = 1

In [17]:
len(data[data[:,1]==0])

0

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [18]:
len(data)

100000

In [19]:
len(np.unique(data[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [20]:
print(len(np.unique(data[:,2])), 'штук')
np.unique(data[:,2])

37 штук


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [21]:
new_data = data[data[:,2] <= 5].copy()

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [22]:
np.max(data[:, 2]/data[:, 1])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [49]:
np.average(data[data[:, 1].argsort()][-100:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [24]:
len(data)

100000

In [25]:
numb = np.random.randint(0, len(data) - 1, 10)
data[numb]

array([[120482,     75,     11],
       [469371,     30,     10],
       [197340,     47,      8],
       [147522,      5,     17],
       [146546,     13,      3],
       [280723,    135,      8],
       [ 57536,    240,     14],
       [ 54864,     30,     10],
       [118325,     60,      7],
       [ 64625,     30,      7]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [26]:
avg_ing = np.average(data[:,2])
len(data[data[:,2]<avg_ing])/len(data)*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [51]:
data_vers = data.copy()
data_vers = np.hstack((data_vers, np.zeros([100000, 1], dtype=np.int32)))
data_vers[np.logical_and(data_vers[:,1]<=20, data_vers[:,2]<=5)] = 1

data_vers

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [     1,      1,      1,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [28]:
np.average(data_vers[:,3])*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [68]:
result = [
    data_vers[data_vers[:,1]<10].tolist(),
    data_vers[np.logical_and(data_vers[:,1]>=10, data_vers[:,1]<20)].tolist(),
    data_vers[data_vers[:,1]<10].tolist(),
]
result[0][2], result[0][2][0]

<ipython-input-68-f566f5cfa75c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = np.array([


([366174, 7, 9, 0], 366174)

In [67]:
max_size = max(len(result[0]), len(result[1]), len(result[2]))
max_size

12815

In [74]:
np.concatenate([
    data_vers[data_vers[:,1]<10][:max_size],
    data_vers[np.logical_and(data_vers[:,1]>=10, data_vers[:,1]<20)][:max_size],
    data_vers[data_vers[:,1]<10][:max_size],
])

array([[ 67660,      5,      6,      0],
       [     1,      1,      1,      1],
       [366174,      7,      9,      0],
       ...,
       [     1,      1,      1,      1],
       [     1,      1,      1,      1],
       [     1,      1,      1,      1]])